# Generated by Django 4.1.13 on 2024-05-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='room_id',
            new_name='room',
        ),
    ]
