# Generated by Django 4.1.13 on 2024-05-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=1000)),
                ('treatment', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'medicalrecord',
            },
        ),
    ]
