# Generated by Django 4.1.13 on 2024-05-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicalrecord',
            table='medical_record',
        ),
    ]
