# Generated by Django 4.1.13 on 2024-05-31 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='BillMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='bill.bill')),
            ],
            options={
                'db_table': 'medicine_bills',
            },
        ),
        migrations.CreateModel(
            name='BillMedicalService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_service_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bill.bill')),
            ],
            options={
                'db_table': 'medical_service_bills',
            },
        ),
    ]
